In [2]:
# imports 
import plotly as plt
import plotly.express as px
import json
from urllib.request import urlopen 
import pandas as pd

In [4]:
data = pd.read_csv('patient.csv')
data.head()

,id,sex,birth_year,country,region,departement,city,group,infection_reason,infection_order,infected_by,contact_number,confirmed_date,released_date,deceased_date,status,health,source,comments
0,NaN,male,NaN,France,Nouvelle-Aquitaine,Charente-Maritime,NaN,NaN,contact with patient,NaN,Creil patient,NaN,2020-02-28,2020-02-03,NaN,released,NaN,CP ARS Nouvelle-Aquitaine,NaN
1,NaN,male,NaN,France,Nouvelle-Aquitaine,Gironde,NaN,NaN,visit to Italy,NaN,NaN,NaN,2020-02-28,NaN,NaN,hospital,good,CP ARS Nouvelle-Aquitaine,NaN
2,NaN,female,NaN,France,Nouvelle-Aquitaine,Landes,NaN,NaN,contact with patient,NaN,Creil patient,NaN,2020-02-28,NaN,NaN,hospital,good,CP ARS Nouvelle-Aquitaine,NaN
3,NaN,male,NaN,France,Nouvelle-Aquitaine,Pyrénées-Atlantiques,NaN,NaN,visit to Italy,NaN,NaN,NaN,2020-03-03,2020-03-06,NaN,released,good,CP ARS Nouvelle-Aquitaine,NaN
4,NaN,male,NaN,France,Nouvelle-Aquitaine,Lot-et-Garonne,NaN,Mulhouse religious gathering,visit to Mulhouse religious gathering,NaN,NaN,NaN,2020-03-05,NaN,NaN,home isolation,good,CP ARS Nouvelle-Aquitaine,NaN

In [19]:
regions = data.groupby('region', as_index=False).size()
regions

                     region  size
0      Auvergne-Rhône-Alpes   228
1   Bourgogne-Franche-Comté   165
2                  Bretagne   157
3       Centre-Val de Loire    20
4                     Corse    63
5                 Grand-Est   461
6                Guadeloupe     1
7                    Guyane     6
8           Hauts-de-France    49
9             Ile-de-France   440
10               La Reunion     5
11               Martinique     6
12                Normandie    25
13       Nouvelle-Aquitaine    87
14                Occitanie   118
15                     PACA   212
16         Pays-de-la-Loire    26
17         Saint-Barthélémy     1
18             Saint-Martin     2

In [14]:
with urlopen('https://raw.githubusercontent.com/codeforamerica/click_that_hood/master/public/data/france-regions.geojson') as response:
 France = json.load(response)

In [23]:
for feature in France['features']:
    print(feature['properties'].get('name'))

Alsace
Lorraine
Corsica
Brittany
Lower Normandy
Upper Normandy
Champagne-Ardenne
Burgundy
Pays-de-la-Loire
Limousin
Midi-Pyrenées
Franche-Comté
Provence-Alpes-Cote d'Azur
Rhone-Alpes
Picardy
Aquitaine
Centre
Ile-de-France
Nord-Pas de Calais
Poitou-Charentes
Auvergne
Languedoc-Roussilion

In [15]:
for feature in France['features']:
    feature['id'] = feature['properties']['name']

In [24]:
#fig = px.choropleth(regions,geojson=France,locations='region',featureidkey='properties.name',color='size',hover_name='region',
    #color_continuous_scale='algae',title="Coronavirus in France")

#fig.update_geos(fitbounds="locations", visible=False)
#fig.write_html('rainforest_loss_chloropleth.html')